name: Create branch from new issue

on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request == null
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}
        fetch-depth: 0  # Important for pushing branches

    - name: Set up Git identity
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Create and push branch
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        ISSUE_TITLE="${{ github.event.issue.title }}"
        SLUG=$(echo "$ISSUE_TITLE" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')
        BRANCH_NAME="issue-${ISSUE_NUMBER}-${SLUG}"

        git checkout -b "$BRANCH_NAME"
        git push origin "$BRANCH_NAME"

